### PR TITLE
Rate function spatial reaction

### PR DESCRIPTION
**Pull request by ilyasku**
This is what I got so far after our discussion in issue #191 . It's not finished yet, so no need to merge it right away, but maybe you can already take a look at it. Rate functions for spatial reactions works only for TT reactions yet, because I ran into some issues with `std::variant` and pushed resolving them aside for now. But I can try to get it working next. 

For structural reactions, there a `_cumulativeRate` gets updated with calls to `GraphTopology::updateReactions`. I implemented an analogous `GraphTopolgy::updateSpatialReactions`, which do not update the `_cumulativeRate`. Instead, the current rates get added to `_cumulativeRate` in the kernels' `EvaluateTopologyReactions::gatherEvents` methods, just as it was with constant rates as well. I hope that is o.k. for dynamic rates, too. I'm not completely sure, because the tests that I implemented in `TestTopologyReactions.cpp` only produce constant rates (the functions simply return a constant). I'll probably have to come up with some distinct tests.

`SpatialTopologyReaction::rate()` throws an error, if the evaluated rate functions leads to a negative rate. First I had a variant where I instead cut it at 0.0, but I think it's more user friendly if the user gets an error, so he/she gets some feedback that there is something wrong with the rate function provided.

### CODE REVIEW

**Review by clonker — COMMENTED** [review]
Very nice! The only thing I would ask is to rebase against the master branch so that the changes run through CI :slightly_smiling_face:

**Comment by clonker** [comment]
Alright so something went wrong when you did the rebase, the commits are duplicates and there are a ton of merge commits. I would recommend doing another rebase (interactive) and in doing that squashing / fixing up these spurious changes. Make sure to have a backup branch with a copy of your changeset before doing that and youll need to force-push afterwards. :slightly_smiling_face:

**Comment by ilyasku** [comment]
Hm, yes, my master branch is suddenly 11 commits ahead of yours, even though I just fetched from your master branch and rebased ... I'll try to fix it.

**Comment by clonker** [comment]
cool, thank you! If you like you can add a python unittest for the python api, otherwise i'm happy to merge.

**Comment by ilyasku** [comment]
Yes, please don't merge yet. I should work on some more tests. When I try to run a simulation with the new feature through the python API it crashes after some time, with an exception that I added where the constant rate is being read even though the rate is set to be dynamic. I have to find out how it comes to that.

**Comment by ilyasku** [comment]
Okay, so in the failing example I had I tried to set dynamic rate between a topology and a particle, which is not implemented. This is handled now by throwing an exception. I did not include this in a test, but added a working test with TT spatial reaction for the python api. I would say it can be merged now.

**Comment by clonker** [comment]
Looks good to me, very nice job!

**Comment by ilyasku** [comment]
Nice, thanks for your help along the way, it was fun to get a bit into pybind11.

**Pull request merged**
