### PR TITLE
Network fusion

### PR DESCRIPTION
**Pull request by ilyasku**
Dear developers, thank you for the nice simulation framework.
I'm interested in simulating cross-linked biopolymer networks with readdy. I added one feature for my simulations, which I happily share, if you think others might find it useful:

* The descriptor language was extended for topology-topology fusion reactions. One can now specify for example `[network>5]`, which is similar to self fusion with `[self=true]`, but checks whether two particles within the same topology are separated by at least 6 edges from each other. 
* Only if the number of edges is larger than the specified value, the fusion can happen.
* This can be used to e.g. have all initial separate polymers fuse to one single network topology.
* With `[self=true]`, I wouldn't be able to do that, since I would not be able to stop direct neighbors within one topology from fusing.
* An example can be seen in the added tests in `readdy/test/TestTopologyReactions.cpp`, where I created a structure of 4 rectangular polymers, that touch each other on the 4 corners and can fuse to one connected topology.

### CODE REVIEW

**Comment by chrisfroe** [comment]
Hi ilyasku,

thanks for the (first external! yay) contribution.

I like this feature! Second-nearest neighbors directly reacting is indeed one shortcoming of the `self=true` type reaction, that one would have to workaround with weird additional dummy types currently. I like this much better. 

Some thoughts to consider before we go into detailed review:
- I would call the `network` parameter simply `distance`, e.g. `[distance>4]`
- Instead of a new type of spatial reaction, I would see this a special case of the `self=true` type reaction. Then the "old" behavior is reproduced by `[distance>0]` without any overhead (the first call to `areConnectedWithNOrLessEdges` directly yields false, which makes any reaction possible. Or just skip the checking altogether).
- In terms of user api, I would make the string `[distance>4]` optional, which is only read when `[self=true]` is also present. If _only_ `[self=true]` is present, the distance parameter defaults to 0. Then _only_ having `[distance>4]` would be invalid and should raise an error.
- Performance _can_ become an issue for large distances and strongly connected graphs, as this does a blind (does not check for already treaded paths) deep search.

I would like to hear @clonker 's thoughts.

**Comment by clonker** [comment]
Hey thanks a lot for your contribution :tada:! I'll check it out this week or beginning of next week. First glance looks good to me, certainly a great addition :)

**Comment by chrisfroe** [comment]
I had a chat with @clonker, I think we can agree on the following points:
- The new functionality should be included in the `TT_ALLOW_SELF` type reaction, instead of a new type of reaction
- Its behavior is determined by the `distance` parameter only (internally the name `min_graph_distance` is probably fine)
  - when `distance` is 0 (and 1?): reproduces the old behavior where every reaction is possible without any overhead calculations
  - when `distance` is 2 or higher: perform the graph search and exclude reaction events as you already implemented
- User API
  - the `[self=true]` must remain a valid input for backward compatibility, that will set the distance parameter to 0
  - `[self=true, distance>6]` is the preferred way of setting the distance parameter
  - for ease of implementation I would exclude the possibility of having `[distance>6]` as valid input, i.e. should raise

@ilyasku would you be ok with realizing these things in this PR? If there are questions we can surely assist you. Anyway, thanks again for the contribution!

**Comment by ilyasku** [comment]
Hi @clonker and @chrisfroe, thank you for your nice feedback.
I will try to implement the points on your list. Looks fine to me, I will let you know if I run into any trouble.

**Comment by ilyasku** [comment]
Hi guys,
I started making the changes, but I'm currently stuck. The tests in `bin/runUnitTests` are passed for SingleCPU, but not for CPU kernel. I tried to include a graph distance check in `CPUEvaluateTopologyReactions::gatherEvents`, as I did before. I want to debug it, but I'm not so experienced in debugging C++. I tried to include several messages with `std::cerr` or `log::warn`, but they never show. It looks like the `gatherEvents` method is never called, but that can hardly be the case. 
The lines of code I want to debug are in `CPUEvaluateTopologyReactions.cpp` in roughly lines 300 to 310. Are there any good means I can use to print some debug messages when I run the tests?

**Comment by clonker** [comment]
The tests on travis seem to run fine, what exactly is going wrong for you?

**Comment by ilyasku** [comment]
Actually, don't know what the problem was. I left it as it was a month ago, removed the messages I used for debugging. The conda build works fine. I had some issues with the copy I built with cmake, but I have even more troubles with that since my last system update somehow. Whatever you did in your conda recipe, you clearly did a better job than I with cmake. :) 
The changes we discussed are implemented now. Let me know what you think.

**Comment by clonker** [comment]
I cannot complain :-) thanks for this nice addition! Cmake can be a bit tricky sometimes, cleaning the cache usually helps though.

**Pull request merged**
