### PR TITLE
Potentials

### PR DESCRIPTION
**Pull request by clonker**
### Changes in architecture / CMake:

* Added tests package for single cpu kernel
* Separated header files from source files in single cpu kernel
* Provided python development settings for better integration with an IDE

### SingleCPU data structure / SingleCPUStateModel:
* Transposed particle data structure, i.e., instead of saving a list of particle objects, save multiple vectors containing the attributes (such as position, type, ...)
* Added (naive) neighbor list functionality
* Encapsulated in a custom ParticleData object: The possibility to deactivate / delete particles:
    * The particle data structure does not decrease in size but rather contains deactivated "ghost" particles to avoid potentially expensive reallocation
    * The deactivation can be performed immediately or by marking the particles and then deactivate them batchwise
    * To still be able to provide random access, the deactivated particles are being swapped to the end of the data structure upon immediate deletion or batch deletion (marking them as such does not change the order, i.e., index is preserved until swapping such that reactions can be realized more easily)
* Handling of potentials order 1 and 2 upon model update (see below)

### Potentials:
* Added potentials of order 1 and 2 (corresponding interfaces, HarmonicRepulsion and Box containment)
* Potentials are understood as time invariants and therefore registered in the Context object
* Upon registration in the context object: Configuration of the potential (ie particle type radii etc)
* Currently: One potential instance per particletype (or pair) necessary, otherwise the configurations get overwritten; this behavior is likely to be changed in a future PR

### Python wrapper:
* Exposed Vec3 (along with the usual operators)
* Exposed more functionality of the Simulation class
* Added the possibility to inject a python-written order-two potential by supplying two python function pointers (calculate_energy and calculate_force) which have wrapped vec3 objects as their input, see python tests
* Added more python tests

### CODE REVIEW

**Comment by franknoe** [comment]
Wow, huge PR! I can't contribute much at this level, just general points:

* let me know when there is an API that can be discussed.
* how do we do documentation at the C++ level? There's not much of that at the moment, I think it would be very useful to at least have a brief description what a class and its methods are doing.

**Comment by clonker** [comment]
Thank you, we will let you know as soon as there is something to discuss!

**Comment by clonker** [comment]
For (c++) documentation purposes I have set up doxygen but admittedly didnt document that much so far (even though it is indeed very useful and important).. will create a gh-pages branch in the next days so there is something to look at as well :-)
.. and then of course try to catch up with the missing documentation!

**Comment by franknoe** [comment]
Yeah, I don't wanna slow down the development cycle by asking for lots 
of text for developer-level code, but I think a brief description of 
what classes and methods are doing is going to be useful even for 
yourself. Clearly, for the API it is important to have an extensive 
documentation.

Am 15/06/16 um 19:41 schrieb Moritz Hoffmann:
>
> For (c++) documentation purposes I have set up doxygen but admittedly 
> didnt document that much so far (even though it is indeed very useful 
> and important).. will create a gh-pages branch in the next days so 
> there is something to look at as well :-)
> .. and then of course try to catch up with the missing documentation!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/readdy/readdy/pull/5#issuecomment-226263226>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/AGMeQpQtDKq5RpHhTlduX8yWFdEuatPoks5qMDk6gaJpZM4I2gZU>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Pull request merged**
